const DEALS_BOARD = '5030964576';
const WORK_BOARD = '5030964591';
const D = {status:'color_mm6qzpdw', value:'numeric_mm6qsr1z', prob:'color_mm6qfj3f', sector:'color_mm6qs9vh', close:'date_mm6qnb0y', tentative:'date_mm6qfe8d'};
const W = {sector:'color_mm6qkvck', exec:'color_mm6q6hyy', billedIncl:'numeric_mm6qxw71', billedEx:'numeric_mm6qnt3z', collectedIncl:'numeric_mm6qdyqq', recv:'numeric_mm6qv7pn', contractIncl:'numeric_mm6qwg7d', contractEx:'numeric_mm6qa7ad'};
const WEIGHTS={high:1,medium:.5,low:.25};
const clean=v=>String(v??'').trim(), norm=v=>clean(v).toLowerCase();
const num=v=>{if(v==null||clean(v)==='')return null;const n=Number(clean(v).replace(/,/g,''));return Number.isFinite(n)?n:null};
const money=v=>{const n=Number(v||0),cr=n/1e7;return Math.abs(cr)>=1?`₹${cr.toFixed(2)} Cr`:`₹${(n/1e5).toFixed(2)} Lakhs`};
const pct=(n,d)=>d?`${(n/d*100).toFixed(1)}%`:'N/A';
const mapRows=items=>items.map(i=>Object.fromEntries(i.column_values.map(c=>[c.id,c.text])));
const headerLike=r=>[D.status,D.prob,D.value,D.sector].some(k=>['deal status','closure probability','masked deal value','sector/service',''].includes(norm(r[k])));
async function gql(query,variables,env){const t=env.MONDAY_API_TOKEN;if(!t)throw Error('MONDAY_API_TOKEN is not configured on the server.');const res=await fetch('https://api.monday.com/v2',{method:'POST',headers:{'content-type':'application/json','authorization':t},body:JSON.stringify({query,variables})});const b=await res.json();if(!res.ok||b.errors)throw Error(b.errors?.map(e=>e.message).join('; ')||`monday API ${res.status}`);return b.data}
async function allItems(board,env){const q=`query($id:ID!){boards(ids:[$id]){items_page(limit:500){cursor items{id name column_values{id text}}}}}`;let p=(await gql(q,{id:board},env)).boards[0]?.items_page;if(!p)throw Error(`Board ${board} was not found or is not accessible.`);let out=p.items||[],c=p.cursor;while(c){p=(await gql(`query($cursor:String!){next_items_page(cursor:$cursor){cursor items{id name column_values{id text}}}}`,{cursor:c},env)).next_items_page;out=out.concat(p.items||[]);c=p.cursor}return out}
async function load(env){const [d,w]=await Promise.all([allItems(DEALS_BOARD,env),allItems(WORK_BOARD,env)]);return{deals:mapRows(d).filter(r=>!headerLike(r)),work:mapRows(w).filter(r=>norm(r[W.sector])!=='sector')}}
const open=deals=>deals.filter(r=>norm(r[D.status])==='open');
function stats(rows){let total=0,weighted=0,valued=0,prob=0,both=0,probValue=0;for(const r of rows){const v=num(r[D.value]),p=WEIGHTS[norm(r[D.prob])];if(v!==null){valued++;total+=v}if(p!==undefined)prob++;if(v!==null&&p!==undefined){both++;weighted+=v*p;probValue+=v}}return{total,weighted,valued,prob,both,probValue,missingValue:rows.length-valued,missingProb:rows.length-prob}}
function sectorStats(rows){const m={};for(const r of rows){const s=clean(r[D.sector])||'Uncategorized',v=num(r[D.value]);m[s]??={value:0,deals:0,missing:0};m[s].deals++;if(v===null)m[s].missing++;else m[s].value+=v}return Object.entries(m).sort((a,b)=>b[1].value-a[1].value)}
const sum=(a,k)=>a.reduce((t,r)=>t+(num(r[k])??0),0), present=(a,k)=>a.filter(r=>num(r[k])!==null).length;
function counts(a,k){const m={};for(const r of a){const s=clean(r[k])||'Missing';m[s]=(m[s]||0)+1}return Object.entries(m).sort((a,b)=>b[1]-a[1])}
function parseDate(v){const d=new Date(clean(v));return clean(v)&&!Number.isNaN(d.getTime())?d:null}
function timeFilter(rows,l){if(!/quarter|q[1-4]|month/.test(l))return{rows,label:null};const now=new Date();let start,end,label;if(/last\s+quarter/.test(l)){const q=Math.floor(now.getUTCMonth()/3)-1;start=new Date(Date.UTC(now.getUTCFullYear()+Math.floor(q/4),((q%4)+4)%4*3,1));end=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+3,1));label='last calendar quarter'}else if(/next\s+quarter/.test(l)){const q=Math.floor(now.getUTCMonth()/3)+1;start=new Date(Date.UTC(now.getUTCFullYear()+Math.floor(q/4),(q%4)*3,1));end=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+3,1));label='next calendar quarter'}else if(/q[1-4]/.test(l)){const q=Number(l.match(/q([1-4])/)[1])-1;start=new Date(Date.UTC(now.getUTCFullYear(),q*3,1));end=new Date(Date.UTC(now.getUTCFullYear(),q*3+3,1));label=`Q${q+1} ${now.getUTCFullYear()}`}else if(/this\s+month/.test(l)){start=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1));end=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,1));label='current calendar month'}else return{rows,label:null};const out=rows.filter(r=>{const d=parseDate(r[D.close])||parseDate(r[D.tentative]);return d&&d>=start&&d<end});return{rows:out,label}}
async function answer(question,env){const {deals,work}=await load(env),l=norm(question),allOpen=open(deals),tf=timeFilter(allOpen,l),rows=tf.label?tf.rows:allOpen,ps=stats(rows);
if(/weighted pipeline|probability.?weighted|probability coverage/.test(l))return `## Probability-Weighted Pipeline\n\n**${money(ps.weighted)}** weighted pipeline\n\n- Open pipeline: ${money(ps.total)}\n- Deals with value + probability: ${ps.both}/${ps.valued}\n- Known probability among open deals: ${ps.prob}/${rows.length} (${pct(ps.prob,rows.length)})\n- Known probability among valued open deals: ${ps.both}/${ps.valued} (${pct(ps.both,ps.valued)})\n- Pipeline value with known probability: ${money(ps.probValue)} / ${money(ps.total)} (${pct(ps.probValue,ps.total)})\n\n**Weighting:** High 100% · Medium 50% · Low 25%\n\n**Data quality:** ${ps.missingProb} open deals missing closure probability; ${ps.missingValue} missing deal value.${tf.label?`\n\nTime filter: ${tf.label}.`:''}`;
if(/data quality|missing data|incomplete|dirty|forecast quality/.test(l)){const missingClose=allOpen.filter(r=>!parseDate(r[D.close])&&!parseDate(r[D.tentative])).length;return `## Data Quality Report\n\n**Deals:** ${deals.length} usable records; ${allOpen.length} open. ${ps.missingValue} open deals missing value; ${ps.missingProb} missing probability; ${missingClose} missing Close/Tentative Close Date.\n\n**Work Orders:** ${work.length} records; financial fields contain blanks that are excluded from sums.\n\n**Actions:** complete missing values/probabilities, improve close-date coverage, and standardize imported labels/header artifacts.`}
if(/billed|collected|receivable/.test(l))return `## Work Order Financials\n\n- **Billed (incl. GST):** ${money(sum(work,W.billedIncl))}\n- **Collected (incl. GST):** ${money(sum(work,W.collectedIncl))}\n- **Receivable:** ${money(sum(work,W.recv))}\n\n**Coverage:** billed ${present(work,W.billedIncl)}/${work.length}; collected ${present(work,W.collectedIncl)}/${work.length}; receivable ${present(work,W.recv)}/${work.length}.`;
if(/compare|execution|work order/.test(l)&&/mining/.test(l)){const md=allOpen.filter(r=>norm(r[D.sector])==='mining'),mw=work.filter(r=>norm(r[W.sector])==='mining');return `## Mining Sector Analysis\n\n**Sales Pipeline**\n- Open deals: ${md.length}\n- Open pipeline: ${money(md.reduce((a,r)=>a+(num(r[D.value])??0),0))}\n\n**Work Orders**\n- Work orders: ${mw.length}\n- Contract (excl. GST): ${money(sum(mw,W.contractEx))}\n- Billed (excl. GST): ${money(sum(mw,W.billedEx))}\n- Collected (incl. GST): ${money(sum(mw,W.collectedIncl))}\n- Receivable: ${money(sum(mw,W.recv))}\n\n**Execution**\n${counts(mw,W.exec).map(([s,n])=>`- ${s}: ${n}`).join('\n')}\n\nSales and operations are distinct datasets; no row-level join is implied.`}
if(/leadership|executive|business update|board update/.test(l)){const ss=stats(allOpen),won=deals.filter(r=>norm(r[D.status])==='won'),wv=won.reduce((a,r)=>a+(num(r[D.value])??0),0),top=sectorStats(allOpen).slice(0,3).map(([s,x])=>`${s} (${money(x.value)})`).join(', '),st=counts(work,W.exec).slice(0,4).map(([s,n])=>`${s}: ${n}`).join(' · ');return `## Leadership Update\n\n**Sales**\n- Open pipeline: ${money(ss.total)} (${allOpen.length} deals)\n- Weighted pipeline: ${money(ss.weighted)}\n- Won: ${won.length} deals (${money(wv)})\n- Top sectors: ${top}\n\n**Operations**\n- Work orders: ${work.length}\n- Execution: ${st}\n\n**Financials**\n- Billed incl. GST: ${money(sum(work,W.billedIncl))}\n- Collected incl. GST: ${money(sum(work,W.collectedIncl))}\n- Receivable: ${money(sum(work,W.recv))}\n\n**Actions**\n- Close missing pipeline-value/probability gaps.\n- Prioritize receivable follow-up.\n- Review concentration in top sectors.`}
if(/sector|pipeline by|top sectors/.test(l))return `## Open Pipeline by Sector\n\n| Sector | Value | Deals | Missing value |\n|---|---:|---:|---:|\n${sectorStats(rows).map(([s,x])=>`| ${s} | ${money(x.value)} | ${x.deals} | ${x.missing} |`).join('\n')}\n\n**Total:** ${money(ps.total)} across ${rows.length} open deals.`;
if(/pipeline|sales|deal funnel/.test(l))return `## Total Open Pipeline\n\n**${money(ps.total)}** across ${rows.length} open deals.\n\n${ps.valued} deals have numeric values; ${ps.missingValue} are missing values.`;
return `I can analyze live monday.com data. Try pipeline, weighted pipeline, pipeline by sector, billed/collected/receivable, data quality, Mining execution, quarter performance, or a leadership update.`}
export async function onRequestPost({request,env}){try{const body=await request.json().catch(()=>({}));const q=clean(body?.question);if(!q)return new Response(JSON.stringify({error:'Question is required'}),{status:400,headers:{'content-type':'application/json'}});const result=await answer(q,env);return new Response(JSON.stringify({answer:result}),{headers:{'content-type':'application/json'}})}catch(e){return new Response(JSON.stringify({error:e?.message||'Unexpected server error'}),{status:500,headers:{'content-type':'application/json'}})}}
