const DEALS_BOARD = process.env.DEALS_BOARD_ID || '5030964576';
const WORK_BOARD = process.env.WORK_ORDERS_BOARD_ID || '5030964591';
const D = { status: 'color_mm6qzpdw', value: 'numeric_mm6qsr1z', prob: 'color_mm6qfj3f', sector: 'color_mm6qs9vh', closeDate: 'date_mm6qnb0y', tentativeCloseDate: 'date_mm6qfe8d', stage: 'color_mm6qwd7q' };
const W = { sector: 'color_mm6qkvck', exec: 'color_mm6q6hyy', billedIncl: 'numeric_mm6qxw71', billedEx: 'numeric_mm6qnt3z', collectedIncl: 'numeric_mm6qdyqq', receivable: 'numeric_mm6qv7pn', contractIncl: 'numeric_mm6qwg7d', contractEx: 'numeric_mm6qa7ad' };
const WEIGHTS = { high: 1, medium: 0.5, low: 0.25 };
function clean(v){return String(v??'').trim()}
function norm(v){return clean(v).toLowerCase()}
function num(v){if(v==null||clean(v)==='')return null;const n=Number(clean(v).replace(/,/g,''));return Number.isFinite(n)?n:null}
function money(v){const n=Number(v||0),cr=n/1e7;return Math.abs(cr)>=1?`₹${cr.toFixed(2)} Cr`:`₹${(n/1e5).toFixed(2)} Lakhs`}
function pct(n,d){return d?`${(n/d*100).toFixed(1)}%`:'N/A'}
function rows(items){return items.map(i=>Object.fromEntries(i.column_values.map(c=>[c.id,c.text])))}
function isHeader(r){return [D.status,D.prob,D.value,D.sector,D.stage].some(k=>{const v=norm(r[k]);return v===norm(k)||['deal status','closure probability','masked deal value','sector/service','deal stage'].includes(v)})}
async function gql(query,variables){const token=process.env.MONDAY_API_TOKEN;if(!token)throw new Error('MONDAY_API_TOKEN is not configured on the server.');const res=await fetch('https://api.monday.com/v2',{method:'POST',headers:{'Content-Type':'application/json','Authorization':token},body:JSON.stringify({query,variables})});const body=await res.json();if(!res.ok||body.errors)throw new Error(body.errors?.map(e=>e.message).join('; ')||`monday API ${res.status}`);return body.data}
async function allItems(boardId){const q=`query($id:ID!){boards(ids:[$id]){items_page(limit:500){cursor items{id name column_values{id text}}}}}`;let p=(await gql(q,{id:boardId})).boards[0]?.items_page;if(!p)throw new Error(`Board ${boardId} was not found or is not accessible.`);let items=p.items||[],cursor=p.cursor;const nq=`query($cursor:String!){next_items_page(cursor:$cursor){cursor items{id name column_values{id text}}}}`;while(cursor){p=(await gql(nq,{cursor})).next_items_page;items=items.concat(p.items||[]);cursor=p.cursor}return items}
async function loadData(){const[d,w]=await Promise.all([allItems(DEALS_BOARD),allItems(WORK_BOARD)]);return{deals:rows(d).filter(r=>!isHeader(r)),work:rows(w).filter(r=>norm(r[W.sector])!=='sector')}}
function openDeals(deals){return deals.filter(r=>norm(r[D.status])==='open')}
function validProbability(r){return Object.prototype.hasOwnProperty.call(WEIGHTS,norm(r[D.prob]))}
function pipelineStats(open){let total=0,weighted=0,valued=0,validProb=0,both=0,probValue=0;for(const r of open){const v=num(r[D.value]),hp=validProbability(r);if(v!==null)valued++;if(hp)validProb++;if(v!==null)total+=v;if(v!==null&&hp){both++;weighted+=v*WEIGHTS[norm(r[D.prob])];probValue+=v}}return{total,weighted,valued,validProb,both,probValue,missingValue:open.length-valued,missingProb:open.length-validProb}}
function sectorStats(open){const m={};for(const r of open){const s=clean(r[D.sector])||'Uncategorized',v=num(r[D.value]);m[s]??={value:0,deals:0,missing:0};m[s].deals++;if(v===null)m[s].missing++;else m[s].value+=v}return Object.entries(m).sort((a,b)=>b[1].value-a[1].value)}
const sum=(a,k)=>a.reduce((x,r)=>x+(num(r[k])??0),0),countNonNull=(a,k)=>a.filter(r=>num(r[k])!==null).length;
function counts(a,k){const m={};for(const r of a){const s=clean(r[k])||'Missing';m[s]=(m[s]||0)+1}return Object.entries(m).sort((a,b)=>b[1]-a[1])}
function parseDate(s){const v=clean(s);if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d}
function quarterRange(base=new Date(),offset=0){const q=Math.floor(base.getUTCMonth()/3),sm=(q+offset)*3,y=base.getUTCFullYear()+Math.floor(sm/12),m=((sm%12)+12)%12;return[new Date(Date.UTC(y,m,1)),new Date(Date.UTC(y,m+3,1))]}
function filterTime(open,l){if(!/(this|current|next|last)?\s*quarter|q[1-4]|this\s+month|last\s+month|next\s+month/.test(l))return{rows:open,label:null};let start,end,label;if(/last\s+quarter/.test(l)){[start,end]=quarterRange(new Date(),-1);label='last calendar quarter'}else if(/next\s+quarter/.test(l)){[start,end]=quarterRange(new Date(),1);label='next calendar quarter'}else if(/q[1-4]/.test(l)){const qn=Number(l.match(/q([1-4])/)[1])-1,y=new Date().getUTCFullYear();start=new Date(Date.UTC(y,qn*3,1));end=new Date(Date.UTC(y,qn*3+3,1));label=`Q${qn+1} ${y}`}else{[start,end]=quarterRange();label='current calendar quarter'}if(/this\s+month|last\s+month|next\s+month/.test(l)){const now=new Date(),shift=/last/.test(l)?-1:/next/.test(l)?1:0,y=now.getUTCFullYear(),m=now.getUTCMonth()+shift;start=new Date(Date.UTC(y,m,1));end=new Date(Date.UTC(y,m+1,1));label=`${shift===-1?'last':shift===1?'next':'current'} calendar month`}const rows=open.filter(r=>{const d=parseDate(r[D.closeDate])||parseDate(r[D.tentativeCloseDate]);return d&&d>=start&&d<end});return{rows,label}}
async function answer(question){const{deals,work}=await loadData(),l=norm(question),allOpen=openDeals(deals),time=filterTime(allOpen,l),open=time.label?time.rows:allOpen,ps=pipelineStats(open);
if(/weighted pipeline|probability.?weighted|probability coverage/.test(l))return`## Probability-Weighted Pipeline\n\n**${money(ps.weighted)}** weighted pipeline\n\n**Key Metrics**\n- Total open pipeline: ${money(ps.total)}\n- Weighted pipeline: ${money(ps.weighted)}\n- Deals with value & probability: ${ps.both}/${ps.valued}\n\n**Probability Coverage**\n- Known probability among all open deals: ${ps.validProb}/${open.length} (${pct(ps.validProb,open.length)})\n- Known probability among open deals with numeric value: ${ps.both}/${ps.valued} (${pct(ps.both,ps.valued)})\n- Probability coverage by pipeline value: ${money(ps.probValue)} / ${money(ps.total)} (${pct(ps.probValue,ps.total)})\n\n**Weighting**\n- High: 100% · Medium: 50% · Low: 25%\n\n**Data Quality**\n- ${ps.missingProb} open deals missing closure probability\n- ${ps.missingValue} open deals missing deal value\n\n${time.label?`**Time filter:** ${time.label}. Dates use Close Date, falling back to Tentative Close Date.`:''}\n\n**Methodology**\nRead live monday.com Deal Funnel records, filtered Deal Status = Open, and applied the probability weights only when both numeric deal value and a valid probability were present.`;
if(/data quality|missing data|incomplete|dirty|forecast quality/.test(l)){const closeMissing=open.filter(r=>!parseDate(r[D.closeDate])&&!parseDate(r[D.tentativeCloseDate])).length;return`## Data Quality Report\n\n**Deal Funnel Data**\n- ${deals.length} usable deal records; ${allOpen.length} open\n- ${ps.missingValue} open deals missing deal value\n- ${ps.missingProb} open deals missing closure probability\n- ${closeMissing} open deals missing both Close Date and Tentative Close Date\n\n**Work Orders**\n- ${work.length} work-order records\n- Billed/collected/receivable fields are sparse; nulls are excluded from sums\n\n**Recommendations**\n1. Complete missing deal values and probabilities.\n2. Improve close-date coverage before quarter forecasting.\n3. Standardize sector/status labels and validate import/header artifacts.`}
if(/billed|collected|receivable/.test(l))return`## Work Order Financials\n\n- **Billed (incl. GST):** ${money(sum(work,W.billedIncl))}\n- **Collected (incl. GST):** ${money(sum(work,W.collectedIncl))}\n- **Receivable:** ${money(sum(work,W.receivable))}\n\n**Coverage**\n- Billed values present: ${countNonNull(work,W.billedIncl)}/${work.length}\n- Collected values present: ${countNonNull(work,W.collectedIncl)}/${work.length}\n- Receivable values present: ${countNonNull(work,W.receivable)}/${work.length}\n\n**Methodology**\nSummed the live Work Order Tracker financial columns; blanks are treated as missing rather than zero.`;
if(/compare|execution|work order/.test(l)&&/mining/.test(l)){const mw=work.filter(r=>norm(r[W.sector])==='mining'),md=allOpen.filter(r=>norm(r[D.sector])==='mining'),mv=md.reduce((a,r)=>a+(num(r[D.value])??0),0);return`## Mining Sector Analysis\n\n**Sales Pipeline**\n- Open deals: ${md.length}\n- Open pipeline: ${money(mv)}\n\n**Operational Execution**\n- Work orders: ${mw.length}\n- Contract value (excl. GST): ${money(sum(mw,W.contractEx))}\n- Billed (excl. GST): ${money(sum(mw,W.billedEx))}\n- Collected (incl. GST): ${money(sum(mw,W.collectedIncl))}\n- Receivable: ${money(sum(mw,W.receivable))}\n\n**Execution Status**\n${counts(mw,W.exec).map(([s,n])=>`- ${s}: ${n}`).join('\n')}\n\nSales pipeline and work-order operations are distinct datasets; no row-level join is implied.`}
if(/leadership|executive|business update|board update/.test(l)){const won=deals.filter(r=>norm(r[D.status])==='won'),wonValue=won.reduce((a,r)=>a+(num(r[D.value])??0),0),top=sectorStats(allOpen).slice(0,3).map(([s,x])=>`${s} (${money(x.value)})`).join(', '),st=counts(work,W.exec);return`## Leadership Update\n\n**Sales Pipeline**\n- Open pipeline: ${money(pipelineStats(allOpen).total)} (${allOpen.length} deals)\n- Weighted pipeline: ${money(pipelineStats(allOpen).weighted)}\n- Won deals: ${won.length} (${money(wonValue)})\n- Top open-pipeline sectors: ${top}\n\n**Operational Execution**\n- Work orders: ${work.length}\n- ${st.slice(0,4).map(([s,n])=>`${s}: ${n}`).join(' · ')}\n\n**Financials**\n- Billed (incl. GST): ${money(sum(work,W.billedIncl))}\n- Collected (incl. GST): ${money(sum(work,W.collectedIncl))}\n- Receivable: ${money(sum(work,W.receivable))}\n\n**Risks & Actions**\n- Close the missing value/probability gaps in the sales pipeline.\n- Prioritize receivable exposure.\n- Review concentration in the largest sales sectors.\n\nSales pipeline and work-order financials are reported separately and are not added together.`}
if(/sector|pipeline by|top sectors/.test(l))return`## Open Pipeline by Sector\n\n| Sector | Value | Deals | Missing value |\n|---|---:|---:|---:|\n${sectorStats(open).map(([s,x])=>`| ${s} | ${money(x.value)} | ${x.deals} | ${x.missing} |`).join('\n')}\n\n**Total:** ${money(ps.total)} across ${open.length} open deals.${time.label?`\n\n**Time filter:** ${time.label}.`:''}\n\nNull/blank deal values are excluded from sector totals and reported as missing.`;
if(/pipeline|deal funnel|sales/.test(l))return`## Total Open Pipeline\n\n**${money(ps.total)}** across ${open.length} open deals.\n\n${ps.valued} deals have numeric values; ${ps.missingValue} are missing values.\n\n${time.label?`**Time filter:** ${time.label}.`:''}\n\nNull/blank deal values are excluded from the total.`;
return`I can analyze the live Deal Funnel and Work Order boards. Try **pipeline, weighted pipeline, pipeline by sector, billed/collected/receivable, data quality, Mining execution, quarter performance, or a leadership update**.`}
module.exports=async(req,res)=>{if(req.method!=='POST')return res.status(405).json({error:'POST only'});try{const q=clean(req.body?.question);if(!q)return res.status(400).json({error:'Question is required'});return res.status(200).json({answer:await answer(q)})}catch(e){return res.status(500).json({error:e.message||'Unexpected server error'})}};